import type { Metadata } from "next";
import "./globals.css";
import { geistSans } from "@/app/ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} min-h-svh bg-background font-sans antialiased`}
      >
        <div className="relative flex min-h-svh flex-col bg-background">
          <div className="border-grid flex flex-1 flex-col">{children}</div>
        </div>
      </body>
    </html>
  );
}
